-- Add All Missing Columns
-- Generated by analyzing production data

-- profiles
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

-- contacts
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS company TEXT;

-- deals
ALTER TABLE deals ADD COLUMN IF NOT EXISTS clerk_org_id UUID;

-- activities
ALTER TABLE activities ADD COLUMN IF NOT EXISTS execution_order INTEGER;

-- meetings
ALTER TABLE meetings ADD COLUMN IF NOT EXISTS calendar_invitees_type JSONB;

-- communication_events
ALTER TABLE communication_events ADD COLUMN IF NOT EXISTS action_items JSONB;

-- workflow_executions
ALTER TABLE workflow_executions ADD COLUMN IF NOT EXISTS action_results JSONB;

