#!/bin/bash

echo "🔍 Checking Fathom Integration Status..."
echo ""
echo "📧 User Email: andrew@sixty.xyz"
echo ""
echo "Please run this SQL query in Supabase SQL Editor:"
echo "https://supabase.com/dashboard/project/ewtuefzeogytgmsnkpmb/editor"
echo ""
echo "==========================================="
echo "SELECT"
echo "    user_id,"
echo "    fathom_user_email,"
echo "    is_active,"
echo "    created_at,"
echo "    token_expires_at,"
echo "    CASE"
echo "        WHEN token_expires_at < NOW() THEN '❌ EXPIRED'"
echo "        WHEN token_expires_at < NOW() + INTERVAL '1 day' THEN '⚠️  EXPIRES SOON'"
echo "        ELSE '✅ VALID'"
echo "    END as token_status"
echo "FROM fathom_integrations"
echo "WHERE fathom_user_email = 'andrew@sixty.xyz';"
echo "==========================================="
echo ""
echo "Expected Result:"
echo "- 1 row returned"
echo "- is_active = true"
echo "- token_status = '✅ VALID'"
echo ""
echo "If NO rows returned:"
echo "  → Go to Settings → Integrations in your CRM"
echo "  → Click 'Connect' or 'Reconnect' Fathom"
echo "  → Follow OAuth flow"
echo ""
echo "If token EXPIRED:"
echo "  → Same as above - reconnect Fathom"
echo ""
