-- Add condensed summary fields to meetings table
-- These fields store AI-generated one-liner summaries for improved UI readability

-- Add new columns for condensed summaries
ALTER TABLE meetings
ADD COLUMN IF NOT EXISTS summary_oneliner TEXT,
ADD COLUMN IF NOT EXISTS next_steps_oneliner TEXT;

-- Add index for searching by condensed summaries
CREATE INDEX IF NOT EXISTS idx_meetings_summary_oneliner ON meetings(summary_oneliner);
CREATE INDEX IF NOT EXISTS idx_meetings_next_steps_oneliner ON meetings(next_steps_oneliner);

-- Add comments for documentation
COMMENT ON COLUMN meetings.summary_oneliner IS 'AI-condensed one-liner (max 15 words) describing what was discussed in the meeting. Generated by Claude Haiku 4.5.';
COMMENT ON COLUMN meetings.next_steps_oneliner IS 'AI-condensed one-liner (max 15 words) describing next steps and action items. Generated by Claude Haiku 4.5.';

-- Backfill strategy note:
-- Existing meetings with summaries can be backfilled by calling the condense-meeting-summary edge function
-- This migration only adds the columns - backfilling should be done via a separate script if needed
