# Memory-optimized Loki configuration
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: warn
  grpc_server_max_recv_msg_size: 4194304  # 4MB
  grpc_server_max_send_msg_size: 4194304  # 4MB

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Memory-optimized ingester
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  
  # Memory limits
  chunk_idle_period: 5m       # Reduced from default
  max_chunk_age: 1h           # Reduced from default
  chunk_target_size: 1048576  # 1MB chunks
  chunk_retain_period: 30s    # Quick cleanup
  max_transfer_retries: 0     # No transfers in single instance
  
  # Memory optimization
  flush_check_period: 30s
  chunk_encoding: snappy      # Better compression

# Query optimization for memory
querier:
  query_ingesters_within: 2h  # Reduced query window
  max_concurrent: 2           # Limit concurrent queries
  
query_range:
  max_retries: 1
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 67108864  # 64MB cache
        ttl: 1h

# Table manager for cleanup
table_manager:
  retention_deletes_enabled: true
  retention_period: 72h  # Keep logs for 3 days only

# Limits to prevent memory issues
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  
  # Query limits
  max_query_series: 500
  max_query_parallelism: 2
  max_streams_per_user: 10000
  max_line_size: 256KB
  max_entries_limit_per_query: 5000
  
  # Ingestion limits  
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_streams_per_user: 0
  max_line_size: 256KB
  
  # Per-stream limits
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 5MB
  
  # Global limits
  max_global_streams_per_user: 5000
  max_chunks_per_query: 2000000
  max_query_time: 60m

# Schema configuration
schema_config:
  configs:
    - from: 2021-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  
  filesystem:
    directory: /loki/chunks

# Compactor for space management
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 1
  
# Ruler configuration (minimal)
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true