-- Add structured process content column to process_maps
-- This stores the JSON representation of the process (nodes, connections, subgraphs)
-- which is the "source of truth" for both Mermaid views and the testing system

-- Add the structured process content column
ALTER TABLE public.process_maps
ADD COLUMN IF NOT EXISTS process_structure JSONB;

-- Add comment explaining the column
COMMENT ON COLUMN public.process_maps.process_structure IS
  'Structured JSON representation of the process (nodes, connections, subgraphs). Generated by Claude Opus, used as source of truth for Mermaid rendering and testing system.';

-- Create GIN index for potential JSONB queries on nodes
CREATE INDEX IF NOT EXISTS idx_process_maps_structure_nodes
ON public.process_maps USING gin ((process_structure -> 'nodes'));

-- Create index for querying by schema version
CREATE INDEX IF NOT EXISTS idx_process_maps_structure_version
ON public.process_maps USING btree ((process_structure ->> 'schemaVersion'));
